packages:
  - 'apps/*'
  - 'packages/*'
catalogs:
  backend:
    express: ^5.1.0
  build:
    '@tailwindcss/vite': ^4.1.8
    '@vitejs/plugin-react': ^4.2.1
    esbuild: ^0.19.0
    vite: ^5.0.8
  cli:
    pncat: ^0.2.4
  dev:
    '@swc-node/register': ^1.10.10
    '@swc/cli': ^0.7.7
    '@swc/core': ^1.11.29
    nodemon: ^3.1.10
    typescript: ^5.8.3
  frontend:
    '@ant-design/x': ^1.4.0
  icons:
    '@ant-design/icons': ^6.0.0
  lint:
    eslint: ^8.55.0
    eslint-plugin-react-hooks: ^4.6.0
    eslint-plugin-react-refresh: ^0.4.5
    prettier: ^3.0.0
  markdown:
    react-markdown: ^10.1.0
  monorepo:
    turbo: ^2.0.0
  network:
    axios: ^1.6.0
  node:
    dotenv: ^16.3.1
  prod:
    '@ai-sdk/openai': ^1.3.22
    '@mastra/core': ^0.10.1
    '@mastra/libsql': ^0.10.0
    '@mastra/loggers': ^0.10.0
    '@mastra/mcp': ^0.10.1
    '@mastra/memory': ^0.10.1
    '@mastra/server': ^0.10.1
    '@modelcontextprotocol/sdk': ^1.0.4
    antd: ^5.25.4
    antd-style: ^3.7.1
    cors: ^2.8.5
    mysql2: ^3.6.1
    qwen-ai-provider: ^0.1.0
    react: ^18.2.0
    react-dom: ^18.2.0
    rehype-highlight: ^7.0.2
    rehype-raw: ^7.0.0
    remark-gfm: ^4.0.1
    rxjs: ^7.8.2
  style:
    tailwindcss: ^4.1.8
  syntax:
    highlight.js: ^11.11.1
  types:
    '@types/cors': ^2.8.17
    '@types/express': ^5.0.2
    '@types/node': ^22.15.24
    '@types/react': ^18.2.43
    '@types/react-dom': ^18.2.17
    '@typescript-eslint/eslint-plugin': ^6.14.0
    '@typescript-eslint/parser': ^6.14.0
  utils:
    dayjs: ^1.11.13
    zod: ^3.25.36
